### ISSUE TITLE
need to make connect-elastic/elastic-init.sh executable before building images

### ISSUE THREAD

**Issue by fermelone** [TendTo/Dotingestion2#2]
Need to make connect-elastic/elastic-init.sh executable before building images:

https://github.com/TendTo/Dotingestion2/blob/master/connect-elastic/elastic-init.sh

A simple: `chmod u+x elastic-init.sh` will do

**Comment by TendTo** [comment]
Yep, it is something I did beforehand on the host and didn't bother checking, but it would be wise to run the command in the Dockerfile
